version: "3"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: post
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: backend
    volumes:
      # - ./backend/uploads:/usr/src/app/uploads
      - ./backend/src:/usr/src/app/src
    ports:
      - 9000:9000
    environment:
      DB_URL: ${DB_URL}
      BACKEND_ENDPOINT: ${BACKEND_ENDPOINT}
      FRONTEND_ENDPOINT: ${FRONTEND_ENDPOINT}

      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      BACKEND_ENDPOINT: ${BACKEND_ENDPOINT}
      FRONTEND_ENDPOINT: ${FRONTEND_ENDPOINT}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
    ports:
      - 3000:3000

volumes:
  dbdata:
